version: '3.8'

services:
  db:
    image: postgres:16
    container_name: cinemabox_db
    environment:
      POSTGRES_DB: cinemabox
      POSTGRES_USER: cinemabox_user
      POSTGRES_PASSWORD: cinemabox_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: