INSERT INTO movies (title, director, year, genre, description, poster_url)
SELECT * FROM (VALUES
    ('The Shawshank Redemption', 'Frank Darabont', 1994, 'Drama', 'Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.', 'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg'),
    ('The Godfather', 'Francis Ford Coppola', 1972, 'Crime', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'),
    ('The Dark Knight', 'Christopher Nolan', 2008, 'Action', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg'),
    ('Pulp Fiction', 'Quentin Tarantino', 1994, 'Crime', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'),
    ('Schindler''s List', 'Steven Spielberg', 1993, 'Drama', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 'https://m.media-amazon.com/images/M/MV5BNDE4OTEyMDMtNTU5Yy00NjY0LTkyYWItMDU1NDhkNGQ5OGI1XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg'),
    ('Inception', 'Christopher Nolan', 2010, 'Sci-Fi', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg'),
    ('The Matrix', 'Lana Wachowski', 1999, 'Sci-Fi', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVlLTM5YTUtZmFhZmJmNmUxYjViXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg'),
    ('Interstellar', 'Christopher Nolan', 2014, 'Sci-Fi', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg'),
    ('Fight Club', 'David Fincher', 1999, 'Drama', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.', 'https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg'),
    ('Goodfellas', 'Martin Scorsese', 1990, 'Crime', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDItZTVmMi00YzE3LWI1YjQtNjFjOThmYzJjNTU2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'),
    ('The Silence of the Lambs', 'Jonathan Demme', 1991, 'Thriller', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMjFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg'),
    ('Parasite', 'Bong Joon-ho', 2019, 'Thriller', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg'),
    ('Spirited Away', 'Hayao Miyazaki', 2001, 'Animation', 'During her family''s move to the suburbs, a sulky 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.', 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ4MDkzNjdlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg'),
    ('The Lord of the Rings: The Return of the King', 'Peter Jackson', 2003, 'Fantasy', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'https://m.media-amazon.com/images/M/MV5BNzA5ZDJhZWMtOWFmNC00Y2ZiLWI2MDEtOTk5YjhmZjExZjFhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'),
    ('Forrest Gump', 'Robert Zemeckis', 1994, 'Drama', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg'),
    ('Whiplash', 'Damien Chazelle', 2014, 'Drama', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student''s potential.', 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg'),
    ('La La Land', 'Damien Chazelle', 2016, 'Romance', 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', 'https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg'),
    ('Joker', 'Todd Phillips', 2019, 'Drama', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.', 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDCtN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg'),
    ('Everything Everywhere All at Once', 'Daniel Kwan', 2022, 'Sci-Fi', 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes connecting with the lives she could have led.', 'https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLTliM2QtYmFhZjAyYjEyMTE1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg')
) AS v(title, director, year, genre, description, poster_url)
WHERE NOT EXISTS (SELECT 1 FROM movies LIMIT 1);